---
apiVersion: v1
kind: Service
metadata:
  name: pydemo
  namespace: apps
spec:
  type: NodePort
  selector:
    app: pydemo
  ports:
    - name: web
      protocol: TCP
      port: 5000
      nodePort: 30050
      targetPort: 5000